### ISSUE TITLE
Features page shows iPhone device with Android OS

### ISSUE THREAD

**Issue by oslego** [openstf/openstf.github.io#2]
Is this intentional?

<img width="1199" alt="screen shot 2015-07-17 at 11 33 51 am" src="https://cloud.githubusercontent.com/assets/63899/8745428/bccfa0e8-2c77-11e5-8f4e-5dd098908b84.png">

**Comment by sorccu** [comment]
Hi,

Yes, you can use STF from an iPhone (and if you add the app to your
homescreen you can get rid of the browser UI). So basically your iPhone
looks like it's running Android.

Unfortunately we had a bit of a regression and it's very, very slow right
now. We'll be improving it again next week.

**Comment by gunta** [comment]
There has been enough questions about this so I will update it to make it explicitly clear.

**Comment by oslego** [comment]
@gunta Yes, it's quite a bit of a nuance for a first-time visitor to observe :)
